[workspace]
members = [
    "xrds-audio",
    "xrds-components",
    "xrds-core",
    "xrds-graphics",
    "xrds-net",
    "xrds-runtime",
]
resolver = "2"

[workspace.dependencies]
safer-ffi = { version = "0.1.13", features = ["headers"] }
