/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __XRDS_CORE_H__
#define __XRDS_CORE_H__
#ifdef __cplusplus
extern "C" {
#endif

/** <No documentation available> */
typedef struct HelloStruct HelloStruct_t;

/** <No documentation available> */
void
xrds_core_destroy_hello (
    HelloStruct_t * ptr);

/** <No documentation available> */
void
xrds_core_hello_rust (
    HelloStruct_t const * st);


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
HelloStruct_t *
xrds_core_new_hello (
    uint64_t x,
    uint64_t y);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __XRDS_CORE_H__ */
