[package]
name = "xrds-runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
xrds-core = { path = "../xrds-core" }

[build-dependencies]
cbindgen = "0.27.0"
