[package]
name = "xrds-editor"
version = "0.1.0"
edition = "2021"
description = "GUI editor application built on top of the XRDS SDK"

[[bin]]
name = "xrds-editor"
path = "src/main.rs"

[dependencies]
xrds = { path = "../../", features = ["editor"] }
xrds-gltf = { workspace = true }
rfd = "0.15"
bevy = { workspace = true }
gltf = "1"
bevy_mod_outline="0.11.0"
egui_extras = "0.34.2"
resvg = "0.44"
usvg = "0.44"